In [1]:
import pandas as pd

In [127]:
from influxdb.line_protocol import quote_literal, quote_ident
from influxdb import DataFrameClient
import os

save_dir = 'result'
os.makedirs(save_dir, exist_ok=True)

# USERNAME = os.environ. get('LYNX_USERNAME')
# PASSWORD = os.environ.get('LYNX_PASSWORD')

client = DataFrameClient(host='ubi-lynx-db.naist.jp', 
                        port=443, 
                        username='lynxadmin', 
                        password='Greenlynx', 
#                         database='whs-3',
                        ssl=True,
                        verify_ssl=True)
def get_label(arg1, arg2):
    measurement = 'sample6'
    text = "SELECT * FROM {} \
            WHERE time > {} AND time < {} \
            ".format(quote_ident(measurement),
                     quote_literal(arg1),
                     quote_literal(arg2))
    rawlabel = client.query(text, database='test')
#     df = rawlabel[measurement].groupby('users').apply(
#             lambda df: df.pivot(columns='user', values='emotion')
#         ).reset_index('users').sort_index()
    df = rawlabel[measurement]
    
    return df
labels = get_label("2021-02-26", "2021-02-27")
labels['20210226']

                           emotion   movieTime  users
2021-02-26 02:16:10+00:00     10.0    0.000000  user1
2021-02-26 02:16:36+00:00     10.0    0.000000  user4
2021-02-26 02:17:49+00:00     10.0    0.000000  user4
2021-02-26 02:19:57+00:00     10.0    0.000000  user3
2021-02-26 02:21:17+00:00     10.0    0.000000  user1
2021-02-26 02:21:49+00:00      3.0   32.226122  user1
2021-02-26 02:21:56+00:00     -4.0   38.914870  user1
2021-02-26 02:22:08+00:00     10.0    0.000000  user1
2021-02-26 02:23:20+00:00     10.0    0.000000  user4
2021-02-26 02:23:55+00:00     10.0    0.000000  user1
2021-02-26 02:24:48+00:00     10.0    0.000000  user4
2021-02-26 02:24:58+00:00     10.0    0.000000  user3
2021-02-26 02:25:04+00:00      1.0   16.101921  user4
2021-02-26 02:25:12+00:00      1.0   77.236485  user1
2021-02-26 02:25:15+00:00      0.0   27.252035  user4
2021-02-26 02:25:18+00:00      0.0   20.895891  user3
2021-02-26 02:25:21+00:00      1.0   32.868793  user4
2021-02-26 02:25:25+00:00      2.0   36.520302  user4
2021-02-26 02:25:34+00:00      1.0   98.992078  user1
2021-02-26 02:25:36+00:00      1.0   48.336940  user4
2021-02-26 02:25:40+00:00      0.0   51.947842  user4
2021-02-26 02:25:45+00:00      1.0   57.078775  user4
2021-02-26 02:25:48+00:00      2.0   59.603680  user4
2021-02-26 02:25:51+00:00      0.0   63.206499  user4
2021-02-26 02:25:53+00:00      1.0   65.104921  user4
2021-02-26 02:26:15+00:00      2.0   86.597203  user4
2021-02-26 02:26:32+00:00      1.0  157.316296  user1
2021-02-26 02:26:40+00:00      1.0  164.675148  user1
2021-02-26 02:26:43+00:00     10.0    0.000000  user2
2021-02-26 02:26:58+00:00      1.0   15.105605  user2
...                            ...         ...    ...
2021-02-26 02:36:12+00:00      3.0  674.028460  user3
2021-02-26 02:36:18+00:00      0.0  574.629370  user2
2021-02-26 02:36:29+00:00      0.0  691.694677  user3
2021-02-26 02:36:29+00:00      3.0  586.097411  user2
2021-02-26 02:36:38+00:00      1.0  700.173577  user3
2021-02-26 02:36:46+00:00      4.0  602.781238  user2
2021-02-26 02:36:51+00:00      2.0  722.927814  user4
2021-02-26 02:36:54+00:00      2.0  779.187701  user1
2021-02-26 02:37:08+00:00      0.0  624.924163  user2
2021-02-26 02:37:34+00:00      2.0  766.128215  user4
2021-02-26 02:37:36+00:00      0.0  821.069761  user1
2021-02-26 02:37:38+00:00      0.0  760.883393  user3
2021-02-26 02:37:42+00:00      1.0  764.260077  user3
2021-02-26 02:38:12+00:00      1.0  804.188321  user4
2021-02-26 02:38:14+00:00      0.0  796.263792  user3
2021-02-26 02:38:28+00:00      2.0  704.816969  user2
2021-02-26 02:38:32+00:00      2.0  876.825359  user1
2021-02-26 02:38:43+00:00      0.0  719.728968  user2
2021-02-26 02:39:06+00:00      1.0  742.500874  user2
2021-02-26 02:39:18+00:00      3.0  754.923282  user2
2021-02-26 02:39:21+00:00      3.0  872.504942  user4
2021-02-26 02:39:28+00:00      0.0  932.402292  user1
2021-02-26 02:39:31+00:00      1.0  873.170389  user3
2021-02-26 02:39:46+00:00     -1.0  898.152294  user4
2021-02-26 02:39:49+00:00      0.0  891.887966  user3
2021-02-26 02:40:07+00:00      0.0  803.467525  user2
2021-02-26 02:40:31+00:00      2.0  828.296759  user2
2021-02-26 02:41:37+00:00      0.0  893.545075  user2
2021-02-26 02:41:53+00:00      1.0  910.148312  user2
2021-02-26 02:42:17+00:00      2.0  934.135272  user2

[141 rows x 3 columns]

In [124]:
data = pd.DataFrame(labels.iloc[9:,:])
data = data.tz_convert('Asia/Tokyo')

In [125]:
data.to_csv('debateSurvey.csv',index=True)

In [126]:
pd.read_csv('debateSurvey.csv')

                    Unnamed: 0  emotion   movieTime  users
0    2021-02-26 11:23:55+09:00     10.0    0.000000  user1
1    2021-02-26 11:24:48+09:00     10.0    0.000000  user4
2    2021-02-26 11:24:58+09:00     10.0    0.000000  user3
3    2021-02-26 11:25:04+09:00      1.0   16.101921  user4
4    2021-02-26 11:25:12+09:00      1.0   77.236485  user1
5    2021-02-26 11:25:15+09:00      0.0   27.252035  user4
6    2021-02-26 11:25:18+09:00      0.0   20.895891  user3
7    2021-02-26 11:25:21+09:00      1.0   32.868793  user4
8    2021-02-26 11:25:25+09:00      2.0   36.520302  user4
9    2021-02-26 11:25:34+09:00      1.0   98.992078  user1
10   2021-02-26 11:25:36+09:00      1.0   48.336940  user4
11   2021-02-26 11:25:40+09:00      0.0   51.947842  user4
12   2021-02-26 11:25:45+09:00      1.0   57.078775  user4
13   2021-02-26 11:25:48+09:00      2.0   59.603680  user4
14   2021-02-26 11:25:51+09:00      0.0   63.206499  user4
15   2021-02-26 11:25:53+09:00      1.0   65.104921  user4
16   2021-02-26 11:26:15+09:00      2.0   86.597203  user4
17   2021-02-26 11:26:32+09:00      1.0  157.316296  user1
18   2021-02-26 11:26:40+09:00      1.0  164.675148  user1
19   2021-02-26 11:26:43+09:00     10.0    0.000000  user2
20   2021-02-26 11:26:58+09:00      1.0   15.105605  user2
21   2021-02-26 11:27:06+09:00      0.0   22.952731  user2
22   2021-02-26 11:27:19+09:00      2.0  204.212072  user1
23   2021-02-26 11:27:19+09:00      0.0   35.986512  user2
24   2021-02-26 11:27:28+09:00      2.0   44.646045  user2
25   2021-02-26 11:27:31+09:00      1.0  153.580220  user3
26   2021-02-26 11:27:34+09:00      3.0  165.635639  user4
27   2021-02-26 11:27:36+09:00     -2.0   53.096498  user2
28   2021-02-26 11:27:52+09:00      2.0  174.869684  user3
29   2021-02-26 11:28:03+09:00      2.0   79.692369  user2
..                         ...      ...         ...    ...
102  2021-02-26 11:36:12+09:00      3.0  674.028460  user3
103  2021-02-26 11:36:18+09:00      0.0  574.629370  user2
104  2021-02-26 11:36:29+09:00      0.0  691.694677  user3
105  2021-02-26 11:36:29+09:00      3.0  586.097411  user2
106  2021-02-26 11:36:38+09:00      1.0  700.173577  user3
107  2021-02-26 11:36:46+09:00      4.0  602.781238  user2
108  2021-02-26 11:36:51+09:00      2.0  722.927814  user4
109  2021-02-26 11:36:54+09:00      2.0  779.187701  user1
110  2021-02-26 11:37:08+09:00      0.0  624.924163  user2
111  2021-02-26 11:37:34+09:00      2.0  766.128215  user4
112  2021-02-26 11:37:36+09:00      0.0  821.069761  user1
113  2021-02-26 11:37:38+09:00      0.0  760.883393  user3
114  2021-02-26 11:37:42+09:00      1.0  764.260077  user3
115  2021-02-26 11:38:12+09:00      1.0  804.188321  user4
116  2021-02-26 11:38:14+09:00      0.0  796.263792  user3
117  2021-02-26 11:38:28+09:00      2.0  704.816969  user2
118  2021-02-26 11:38:32+09:00      2.0  876.825359  user1
119  2021-02-26 11:38:43+09:00      0.0  719.728968  user2
120  2021-02-26 11:39:06+09:00      1.0  742.500874  user2
121  2021-02-26 11:39:18+09:00      3.0  754.923282  user2
122  2021-02-26 11:39:21+09:00      3.0  872.504942  user4
123  2021-02-26 11:39:28+09:00      0.0  932.402292  user1
124  2021-02-26 11:39:31+09:00      1.0  873.170389  user3
125  2021-02-26 11:39:46+09:00     -1.0  898.152294  user4
126  2021-02-26 11:39:49+09:00      0.0  891.887966  user3
127  2021-02-26 11:40:07+09:00      0.0  803.467525  user2
128  2021-02-26 11:40:31+09:00      2.0  828.296759  user2
129  2021-02-26 11:41:37+09:00      0.0  893.545075  user2
130  2021-02-26 11:41:53+09:00      1.0  910.148312  user2
131  2021-02-26 11:42:17+09:00      2.0  934.135272  user2

[132 rows x 4 columns]

# user1

In [90]:
user1 = labels.query('users=="user1"')

In [91]:
user1

                           emotion   movieTime  users
2021-02-26 02:16:10+00:00     10.0    0.000000  user1
2021-02-26 02:21:17+00:00     10.0    0.000000  user1
2021-02-26 02:21:49+00:00      3.0   32.226122  user1
2021-02-26 02:21:56+00:00     -4.0   38.914870  user1
2021-02-26 02:22:08+00:00     10.0    0.000000  user1
2021-02-26 02:23:55+00:00     10.0    0.000000  user1
2021-02-26 02:25:12+00:00      1.0   77.236485  user1
2021-02-26 02:25:34+00:00      1.0   98.992078  user1
2021-02-26 02:26:32+00:00      1.0  157.316296  user1
2021-02-26 02:26:40+00:00      1.0  164.675148  user1
2021-02-26 02:27:19+00:00      2.0  204.212072  user1
2021-02-26 02:28:32+00:00      3.0  276.862978  user1
2021-02-26 02:29:12+00:00      1.0  316.466579  user1
2021-02-26 02:29:53+00:00      1.0  358.120497  user1
2021-02-26 02:30:08+00:00      1.0  373.277116  user1
2021-02-26 02:30:37+00:00      2.0  401.857739  user1
2021-02-26 02:32:06+00:00      3.0  490.674467  user1
2021-02-26 02:32:54+00:00     -1.0  538.444528  user1
2021-02-26 02:33:38+00:00      1.0  583.353314  user1
2021-02-26 02:34:19+00:00      1.0  623.650547  user1
2021-02-26 02:34:34+00:00      0.0  639.007090  user1
2021-02-26 02:35:12+00:00      2.0  676.490045  user1

# user2

In [92]:
user2 = labels.query('users=="user2"')

In [93]:
user2

                           emotion   movieTime  users
2021-02-26 02:26:43+00:00     10.0    0.000000  user2
2021-02-26 02:26:58+00:00      1.0   15.105605  user2
2021-02-26 02:27:06+00:00      0.0   22.952731  user2
2021-02-26 02:27:19+00:00      0.0   35.986512  user2
2021-02-26 02:27:28+00:00      2.0   44.646045  user2
2021-02-26 02:27:36+00:00     -2.0   53.096498  user2
2021-02-26 02:28:03+00:00      2.0   79.692369  user2
2021-02-26 02:28:32+00:00      1.0  108.759619  user2
2021-02-26 02:28:49+00:00      0.0  125.304462  user2
2021-02-26 02:29:39+00:00      2.0  175.868900  user2
2021-02-26 02:30:08+00:00      1.0  204.730908  user2
2021-02-26 02:30:15+00:00      0.0  211.525629  user2
2021-02-26 02:30:30+00:00      2.0  226.801903  user2
2021-02-26 02:30:37+00:00      4.0  234.209901  user2
2021-02-26 02:31:40+00:00      0.0  296.443513  user2
2021-02-26 02:31:46+00:00      2.0  302.301232  user2
2021-02-26 02:32:31+00:00      1.0  347.556429  user2
2021-02-26 02:32:44+00:00      2.0  360.807848  user2
2021-02-26 02:33:44+00:00      0.0  421.004552  user2
2021-02-26 02:33:54+00:00      2.0  430.787363  user2
2021-02-26 02:34:06+00:00      3.0  443.273939  user2
2021-02-26 02:34:15+00:00      0.0  451.642701  user2
2021-02-26 02:34:25+00:00      1.0  461.601658  user2
2021-02-26 02:35:20+00:00      0.0  516.298105  user2

# user3

In [94]:
user3 = labels.query('users=="user3"')

In [95]:
user3

                           emotion   movieTime  users
2021-02-26 02:19:57+00:00     10.0    0.000000  user3
2021-02-26 02:24:58+00:00     10.0    0.000000  user3
2021-02-26 02:25:18+00:00      0.0   20.895891  user3
2021-02-26 02:27:31+00:00      1.0  153.580220  user3
2021-02-26 02:27:52+00:00      2.0  174.869684  user3
2021-02-26 02:28:08+00:00      3.0  190.387150  user3
2021-02-26 02:28:17+00:00      0.0  199.581159  user3
2021-02-26 02:28:20+00:00      1.0  202.693309  user3
2021-02-26 02:28:28+00:00      0.0  210.648007  user3
2021-02-26 02:28:40+00:00      2.0  222.576553  user3
2021-02-26 02:28:51+00:00      3.0  233.791038  user3
2021-02-26 02:29:13+00:00      0.0  255.586672  user3
2021-02-26 02:29:17+00:00      2.0  259.300606  user3
2021-02-26 02:29:29+00:00      3.0  271.453674  user3
2021-02-26 02:29:54+00:00      0.0  296.945109  user3
2021-02-26 02:29:59+00:00      1.0  301.674087  user3
2021-02-26 02:30:33+00:00      0.0  335.687395  user3
2021-02-26 02:31:18+00:00      2.0  380.837174  user3
2021-02-26 02:31:39+00:00      0.0  401.588865  user3
2021-02-26 02:32:07+00:00      1.0  429.427101  user3
2021-02-26 02:32:24+00:00      0.0  446.327668  user3
2021-02-26 02:32:29+00:00      1.0  451.856147  user3
2021-02-26 02:32:34+00:00      2.0  456.916263  user3
2021-02-26 02:32:58+00:00      0.0  480.165924  user3
2021-02-26 02:33:01+00:00      1.0  483.414502  user3
2021-02-26 02:33:31+00:00      0.0  513.959697  user3
2021-02-26 02:33:41+00:00      2.0  523.528854  user3
2021-02-26 02:34:08+00:00      0.0  550.406901  user3
2021-02-26 02:34:11+00:00      4.0  553.781703  user3
2021-02-26 02:34:12+00:00      0.0  554.961061  user3
2021-02-26 02:35:11+00:00      1.0  613.954641  user3
2021-02-26 02:35:15+00:00      4.0  617.932763  user3
2021-02-26 02:35:20+00:00      0.0  621.984747  user3

# user4

In [96]:
user4 = labels.query('users=="user4"')

In [97]:
user4

                           emotion   movieTime  users
2021-02-26 02:16:36+00:00     10.0    0.000000  user4
2021-02-26 02:17:49+00:00     10.0    0.000000  user4
2021-02-26 02:23:20+00:00     10.0    0.000000  user4
2021-02-26 02:24:48+00:00     10.0    0.000000  user4
2021-02-26 02:25:04+00:00      1.0   16.101921  user4
2021-02-26 02:25:15+00:00      0.0   27.252035  user4
2021-02-26 02:25:21+00:00      1.0   32.868793  user4
2021-02-26 02:25:25+00:00      2.0   36.520302  user4
2021-02-26 02:25:36+00:00      1.0   48.336940  user4
2021-02-26 02:25:40+00:00      0.0   51.947842  user4
2021-02-26 02:25:45+00:00      1.0   57.078775  user4
2021-02-26 02:25:48+00:00      2.0   59.603680  user4
2021-02-26 02:25:51+00:00      0.0   63.206499  user4
2021-02-26 02:25:53+00:00      1.0   65.104921  user4
2021-02-26 02:26:15+00:00      2.0   86.597203  user4
2021-02-26 02:27:34+00:00      3.0  165.635639  user4
2021-02-26 02:28:30+00:00      2.0  221.824954  user4
2021-02-26 02:29:09+00:00      2.0  261.066840  user4
2021-02-26 02:30:34+00:00      1.0  346.094029  user4
2021-02-26 02:31:08+00:00      3.0  380.318536  user4
2021-02-26 02:31:52+00:00      2.0  423.697310  user4
2021-02-26 02:32:59+00:00      1.0  490.475685  user4
2021-02-26 02:34:13+00:00      2.0  564.584510  user4
2021-02-26 02:35:05+00:00      2.0  616.826260  user4